# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: widowx
  joint_model_group_pose: watch
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - gripper_prismatic_joint_1
    - gripper_prismatic_joint_2
    - gripper_revolute_joint
    - rim_back_joint
    - roller_n_rim_back_joint
    - roller_ne_rim_back_joint
    - roller_nw_rim_back_joint
    - roller_s_rim_back_joint
    - roller_se_rim_back_joint
    - roller_sw_rim_back_joint
    - rim_left_joint
    - roller_n_rim_left_joint
    - roller_ne_rim_left_joint
    - roller_nw_rim_left_joint
    - roller_s_rim_left_joint
    - roller_se_rim_left_joint
    - roller_sw_rim_left_joint
    - rim_right_joint
    - roller_n_rim_right_joint
    - roller_ne_rim_right_joint
    - roller_nw_rim_right_joint
    - roller_s_rim_right_joint
    - roller_se_rim_right_joint
    - roller_sw_rim_right_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: /demo_DIR/joint_trajectory_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
  - name: /demo_DIR/hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - gripper_prismatic_joint_1
      - gripper_prismatic_joint_2